name: Feature request
description: Create a feature request
title: "[feat]: "
labels: ["✨ enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new issue.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request.
      placeholder: "I think this feature would be great because..."
      value: "Describe your feature request..."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List the tasks needed to complete this feature.
      value: |
        - [ ]
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature here.
      placeholder: ex. screenshots, Stack Overflow links, forum links, etc.
      value: "Additional details here..."
    validations:
      required: false
